language: scala
script:
  - cd ./PizzaTime/
  - sbt ++$TRAVIS_SCALA_VERSION compile
  - sbt ++$TRAVIS_SCALA_VERSION test
scala:
  - 2.13.2
jdk:
  - openjdk8
before_install:
  - sudo apt update
  - sudo apt install openjfx